
#======================================
#        Database
#======================================
spring:
  datasource:
    url: jdbc:mysql://localhost3306/book_management_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    username: username
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle-size: 5
      idle-timeout: 30000
      connection-timeout: 20000
      max-lifetime: 45000

#======================================
#        JPA/Hibernate
#======================================
  jpa:
    hibernate:
      ddl-auto: auto
    show_sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
        naming:
          physical_strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

#======================================
#        Validation
#======================================

  messages:
    basename: messages
#======================================
#        Server
#======================================
server:
  port: 9090
  servlet:
    application-display-name: Book Management System

#======================================
#        Idempotency Cleanup
#======================================
idempotency:
  retention-days: 7
  cleanup:
    cron: "0 0 0 * * *"
#======================================
#        Logging
#======================================
logging:
  level:
    org.springframework: INFO
    com.example.bookmanagement: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} %clr(%-5level) %clr(%logger{35}){cyan} : %msg%n"
#======================================
#        Actuator
#======================================
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
#======================================
#        Database
#======================================
lombok:
  anyconstructor:
    supperssconstructorproperties: true







